### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by navierula** [muttflapper/pwp-capstones#1]
**Valid Python Code (4/4)**
Code included runs without any errors.

**Implementation of Project Requirements (4/4)**
Code produces the suite of functions and classes required of it and calls them in an appropriate order.

**Software Architecture (4/4)**
Code is separated into distinct classes and functions each which are invoked for their own purposes. 

**Uses Python Language Features (3/4)**
Code uses language features appropriately. However, more research could have been done in this area. For example, the regular expressions library or the string library may have been helpful in regards to text cleaning.

**Produces Accurate Output (4/4)**
Code output is properly formatted and accurate.

---

Great job on this project, especially in terms of class usage and code organization. I also appreciated that you included comments within your code so that those reading your program can understand what's going on. Instead of directly printing out the name of the suspect, it'd be awesome if you could extend the program by creating a function to print the name of the suspect based on the highest percentage. Other than that, good job!

**Comment by meanmodemoda** [comment]
Thank you! I appreciate your time reviewing. Yes I was running low on time and did skip the last part to print out the name using a function. :-P
